version: '3.8'
services:
  api:
    container_name: queue-app-api
    image: queue-app-api
    build: .
    env_file:
      - .env
    ports:
      - 80:80

  test-db:
    image: postgres:13
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests

